# Generated by Django 4.2.8 on 2023-12-20 17:25

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ejra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField()),
                ('free_capacity', models.IntegerField()),
                ('min_ticket', models.IntegerField()),
                ('max_ticket', models.IntegerField()),
                ('start_sale_date', django_jalali.db.models.jDateTimeField()),
                ('end_sale_date', django_jalali.db.models.jDateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='rooydad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='sans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateTimeField()),
                ('ejra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.ejra')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('rooydad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.rooydad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
        migrations.AddField(
            model_name='ejra',
            name='rooydad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.rooydad'),
        ),
    ]
