# Generated by Django 4.2.8 on 2024-01-01 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'بلیت'},
        ),
    ]
